

CREATE TABLE CatalogSupplier(item INT NOT NULL);
ALTER TABLE CatalogSupplier ADD number VARCHAR(30) NOT NULL;
ALTER TABLE CatalogSupplier ADD type ENUM ('service', 'item') NOT NULL;
ALTER TABLE CatalogSupplier ADD brief VARCHAR(256) NOT NULL;
ALTER TABLE CatalogSupplier ADD COLUMN factoryID VARCHAR(100);
ALTER TABLE CatalogSupplier ADD COLUMN providerID VARCHAR(100);
ALTER TABLE CatalogSupplier ADD COLUMN ref1 VARCHAR(100);
ALTER TABLE CatalogSupplier ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Entities(id);
ALTER TABLE CatalogSupplier ADD CONSTRAINT PRIMARY KEY (item);
ALTER TABLE CatalogSupplier ADD CONSTRAINT UNIQUE (number);


CREATE TABLE CatalogClient(item INT NOT NULL);
ALTER TABLE CatalogClient ADD number VARCHAR(30) NOT NULL;
ALTER TABLE CatalogClient ADD type ENUM ('service', 'item') NOT NULL;
ALTER TABLE CatalogClient ADD brief VARCHAR(256) NOT NULL;
ALTER TABLE CatalogClient ADD COLUMN ref1 VARCHAR(100);
ALTER TABLE CatalogClient ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Entities(id);
ALTER TABLE CatalogClient ADD CONSTRAINT PRIMARY KEY (item);
ALTER TABLE CatalogClient ADD CONSTRAINT UNIQUE (number);


CREATE TABLE Stock(item INT NOT NULL PRIMARY KEY,number VARCHAR(30) NOT NULL, quantity INT DEFAULT 0);
ALTER TABLE Stock ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Catalog(item);
ALTER TABLE Stock ADD COLUMN warehouse VARCHAR(100);
ALTER TABLE Stock ADD COLUMN position VARCHAR(50);
