

CREATE TABLE Catalog(item INT NOT NULL);
ALTER TABLE Catalog ADD number VARCHAR(30) NOT NULL;
-- mode: cliente: C, proveedor : S
ALTER TABLE Catalog ADD mode ENUM ('S', 'C') NOT NULL;
ALTER TABLE Catalog ADD type ENUM ('S', 'M') NOT NULL;
ALTER TABLE Catalog ADD brief VARCHAR(256) NOT NULL;
ALTER TABLE Catalog ADD COLUMN factoryID VARCHAR(100);
ALTER TABLE Catalog ADD COLUMN providerID VARCHAR(100);
ALTER TABLE Catalog ADD COLUMN ref1 VARCHAR(100);
ALTER TABLE Catalog ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Entities(id);
ALTER TABLE Catalog ADD CONSTRAINT PRIMARY KEY (item);
ALTER TABLE Catalog ADD CONSTRAINT UNIQUE (number);

CREATE TABLE Stock(item INT NOT NULL PRIMARY KEY,number VARCHAR(30) NOT NULL, quantity INT DEFAULT 0);
ALTER TABLE Stock ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Catalog(item);
ALTER TABLE Stock ADD COLUMN warehouse VARCHAR(100);
ALTER TABLE Stock ADD COLUMN position VARCHAR(50);
