

CREATE TABLE Catalog(ente INT NOT NULL,number VARCHAR(30) NOT NULL, type ENUM ('S', 'M') NOT NULL,brief VARCHAR(256) NOT NULL,FOREIGN KEY(ente) REFERENCES Entities(id));
ALTER TABLE Catalog ADD CONSTRAINT ente_unique PRIMARY KEY (ente);
ALTER TABLE Catalog ADD CONSTRAINT number_unique UNIQUE (number);



CREATE TABLE Stock(item INT NOT NULL PRIMARY KEY,number VARCHAR(30) NOT NULL, quantity INT DEFAULT 0, FOREIGN KEY(item) REFERENCES Catalog(ente));
ALTER TABLE Stock ADD COLUMN position VARCHAR(50);
ALTER TABLE Stock ADD COLUMN warehouse VARCHAR(100);
