

CREATE TABLE Buys (doc INT NOT NULL);
ALTER TABLE Buys ADD supplier INT NOT NULL;
ALTER TABLE Buys ADD status ENUM ('creating','created','quoting','quoted','buyed') NOT NULL DEFAULT 'creating';
ALTER TABLE Buys ADD date DATETIME DEFAULT NOW();
ALTER TABLE Buys ADD CONSTRAINT FOREIGN KEY(doc) REFERENCES Entities(id);
ALTER TABLE Buys ADD CONSTRAINT PRIMARY KEY(doc);
ALTER TABLE Buys ADD CONSTRAINT FOREIGN KEY(supplier) REFERENCES Supplier(supplier);
