
CREATE TABLE Catalog(item INT NOT NULL);
ALTER TABLE Catalog ADD number VARCHAR(30) NOT NULL;
ALTER TABLE Catalog ADD type ENUM ('service', 'item') NOT NULL;
ALTER TABLE Catalog ADD mode ENUM ('I', 'O') NOT NULL;
ALTER TABLE Catalog ADD brief VARCHAR(256) NOT NULL;
ALTER TABLE Catalog ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Entities(id);
ALTER TABLE Catalog ADD CONSTRAINT PRIMARY KEY (item);
ALTER TABLE Catalog ADD CONSTRAINT UNIQUE (number);


CREATE TABLE CatalogSupplier(item INT NOT NULL);
ALTER TABLE CatalogSupplier ADD COLUMN factoryID VARCHAR(100);
ALTER TABLE CatalogSupplier ADD COLUMN providerID VARCHAR(100);
ALTER TABLE CatalogSupplier ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Catalog(item);
ALTER TABLE CatalogSupplier ADD CONSTRAINT PRIMARY KEY (item);


CREATE TABLE CatalogClient(item INT NOT NULL);
ALTER TABLE CatalogClient ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Catalog(item);
ALTER TABLE CatalogClient ADD CONSTRAINT PRIMARY KEY (item);


CREATE TABLE Stock(item INT NOT NULL PRIMARY KEY,number VARCHAR(30) NOT NULL, quantity INT DEFAULT 0);
ALTER TABLE Stock ADD CONSTRAINT FOREIGN KEY(item) REFERENCES Entities(id);
ALTER TABLE Stock ADD COLUMN warehouse VARCHAR(100);
ALTER TABLE Stock ADD COLUMN position VARCHAR(50);
