


CREATE TABLE Permission(permission INT PRIMARY KEY NOT NULL,name VARCHAR(20) NOT NULL,brief VARCHAR(256) NOT NULL,FOREIGN KEY(permission) REFERENCES Ente(id));

CREATE TABLE User_Permission(up INT NOT NULL PRIMARY KEY,user INT NOT NULL,permission INT NOT NULL,FOREIGN KEY(permission) REFERENCES Permission(permission),FOREIGN KEY(user) REFERENCES User(user), FOREIGN KEY(up) REFERENCES Ente(id));

