#!/bin/bash

rm -f ~/develop/sysapp/html/sysapp-html/*~


cp -r -u  ~/develop/sysapp/html/sysapp-html/* /var/www/sysapp

if [ ! -d "/var/www/sysapp/theme/gnome-2.91" ] ; then
	if [ ! -f "gnome-icon-theme-2.91.93.tar.bz2" ]; then
		wget https://download.gnome.org/sources/gnome-icon-theme/2.91/gnome-icon-theme-2.91.93.tar.bz2
	fi
	mkdir gnome-2.91
	tar -xjf gnome-icon-theme-2.91.93.tar.bz2 -C gnome-2.91 --strip-components=1
	mkdir -p /var/www/sysapp/theme/gnome-2.91
	mv gnome-2.91/gnome/* /var/www/sysapp/theme/gnome-2.91
	rm -r gnome-2.91
fi

