#!/bin/bash

#WEBDIRECTORY="/var/www/localhost/htdocs"
#WEBDIRECTORY="/var/www/muposys"
#WEBDIRECTORY="/var/www/html/"
WEBDIRECTORY="/srv/http/"

rm -f /home/azael/develop/octetos/muposys/html/muposys-html/*~


cp -r -u -f /home/azael/develop/octetos/muposys/html/muposys-html/* $WEBDIRECTORY

if [ ! -d "$WEBDIRECTORY/theme/gnome-2.91" ] ; then
	if [ ! -f "gnome-icon-theme-2.91.93.tar.bz2" ]; then
		wget https://download.gnome.org/sources/gnome-icon-theme/2.91/gnome-icon-theme-2.91.93.tar.bz2
	fi
	mkdir gnome-2.91
	tar -xjf gnome-icon-theme-2.91.93.tar.bz2 -C gnome-2.91 --strip-components=1
	mkdir -p $WEBDIRECTORY/theme/gnome-2.91
	mv gnome-2.91/gnome/* $WEBDIRECTORY/theme/gnome-2.91/
	rm -r gnome-2.91
fi

#chown www-data:www-data -R /var/www
#chmod u+w /var/www
