
package octetos.muposys;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import octetos.muposys.db.Users;

import org.xml.sax.SAXException;

/**
 *
 * @author azael
 */
public class Loggin extends javax.swing.JInternalFrame {

    private Desktop desktop;
    
    
    /**
     * Creates new form Loggin
     */
    public Loggin(Desktop d) {
        initComponents();
        setTitle("Inicio de Sesion.");
        desktop = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txUser = new javax.swing.JTextField();
        btAccept = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        txpwd = new javax.swing.JPasswordField();

        jLabel1.setText("Usuarios : ");

        jLabel2.setText("Contraseña : ");

        btAccept.setText("Aceptar");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        btCancel.setText("Cencelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(txUser, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txpwd)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAccept)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAccept)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        Configuration config = null;
        try 
        {
            config = new Configuration();
        }
        catch (ParserConfigurationException | SAXException | IOException ex) 
        {
            Logger.getLogger(Loggin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        octetos.db.maria.Datconnect dat = new octetos.db.maria.Datconnect(config.getDataSource());
        
        octetos.db.maria.Connector connector = new octetos.db.maria.Connector();
        boolean checkConection = false;
        try
        {
            checkConection = connector.connect(dat);
        }
        catch(java.sql.SQLException e)            
        {
            e.printStackTrace(); 
        }   
        
        String where = "status = 'A' and name = '" + txUser.getText() + "'";
        ArrayList<Users> lsuser = null;
        boolean check = false;
        Users user= null;
        try 
        {
            lsuser = user.select(connector,where,2);
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(Loggin.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(this, "Contraseña incorrecta","Usauario/Contraseña incorrectos",JOptionPane.ERROR_MESSAGE);
            return;
        }
        finally
        {
            try
            {
                connector.close();
            }
            catch(java.sql.SQLException e)            
            {
                e.printStackTrace(); 

            }
        }   
        
        if(lsuser.size() > 1)
        {
            JOptionPane.showMessageDialog(this, "Nombre de usuario ambiguo","Usauario/Contraseña incorrectos ",JOptionPane.ERROR_MESSAGE);
        }
        else if(lsuser.size() == 0)
        {
            JOptionPane.showMessageDialog(this, "Usuario desconocido","Usauario/Contraseña incorrectos ",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            user = lsuser.get(0);
            try
            {
                boolean nameD = user.downName(connector);
                if(!nameD)
                {
                    JOptionPane.showMessageDialog(this, "Fallo la descarga de Name.","Usauario/Contraseña incorrectos ",JOptionPane.ERROR_MESSAGE);
                }
                boolean pwdD = user.downPwdtxt(connector);
                if(!pwdD)
                {
                    JOptionPane.showMessageDialog(this, "Fallo la descarga de Contrasena.","Usauario/Contraseña incorrectos ",JOptionPane.ERROR_MESSAGE);
                }
                if(nameD && pwdD)
                {
                    if(user.getName().compareTo(txUser.getText()) == 0 && user.getPwdtxt().compareTo(txpwd.getText()) == 0)
                    {
                        check = true;                    
                    }
                }
            }
            catch(java.sql.SQLException e)
            {
                
            }
        }
         
        try
        {
            connector.close();
        }
        catch(java.sql.SQLException e)            
        {
            e.printStackTrace();
        }
        if(check)
        {
            desktop.enableApplication();
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta " + user.getName() + " " + txpwd.getText(),"Usauario/Contraseña incorrectos ",JOptionPane.ERROR_MESSAGE);
        }            
    }//GEN-LAST:event_btAcceptActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txUser;
    private javax.swing.JPasswordField txpwd;
    // End of variables declaration//GEN-END:variables
}
