#!/bin/bash

MIDDLESERVER=""
CGISERVER=""
DISTRO=$(lsb_release -i | cut -c 16- | xargs)
case $DISTRO in
	ManjaroLinux)   
		MIDDLESERVER="srv/http"
		CGISERVER="srv/cgi"
	;;
	*)
	echo "Servidor desconocido."
esac
DOCUMENTROOT=""

if [ "$1" ]; then
  DOCUMENTROOT=$1
else
  echo "Deve indicar el Documento raiz para el servidor"
  exit
fi
SITE=""
if [ "$2" ]; then
  SITE=$2
else
  echo "Deve indicar el Documento raiz para el servidor"
  exit
fi

SERVER="$DOCUMENTROOT/$MIDDLESERVER/$SITE"
CGI="$DOCUMENTROOT/$CGISERVER/$SITE"
#echo $SERVER

cp bin/Debug/login $CGI/
