#!/bin/bash

MIDDLESERVER=""
CGISERVER=""
DISTRO=$(lsb_release -i | cut -c 16- | xargs)
case $DISTRO in
	ManjaroLinux)   
		MIDDLESERVER="srv/http"
		CGISERVER="srv/cgi"
	;;
	*)
	echo "Servidor desconocido."
esac
DOCUMENTROOT=""

if [ "$1" ]; then
  DOCUMENTROOT=$1
else
  echo "Deve indicar el Documento raiz para el servidor"
  exit
fi
SITE=""
if [ "$2" ]; then
  SITE=$2
else
  echo "Deve indicar el Documento raiz para el servidor"
  exit
fi

SERVER="$DOCUMENTROOT/$MIDDLESERVER/$SITE"
CGI="$SERVER/cgi"
#echo $SERVER

mkdir -p $CGI
cp bin/Debug/login $CGI/login.cgi
cp ../../core/bin/Debug/liboctetos-core-3.so $CGI
cp ../../cave/bin/Debug/libcave-mmsql-0.so $CGI
cp ../../cave/bin/Debug/libcave-mmsql-1.so $CGI
cp ../core/bin/Debug/libmuposys-core-1.so $CGI
cp bin/Debug/libmuposys-web-1.so $CGI
